# Generated by Django 4.0.2 on 2022-02-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, default='xxx.jpg', null=True, upload_to=''),
        ),
    ]
